name: CI MiniBlog

on:
  push:
    branches:
      - docs/kubernetes-minikube

  workflow_dispatch:

jobs:
  probar:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: secreto
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: 03-09-2026/miniblog

    env:
      DB_HOST: localhost

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Configurar Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: python -m pytest -v